spring:
  application:
    name: Helm Storing Full application properties into the ConfigMap
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-helm-cm:5432/helm_cm?currentSchema=helmcm
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      pool-name: HikariCP
  jpa:
    properties:
      hibernate:
        default_schema: helmcm
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations:
      - classpath:db/migration/structure
      - classpath:db/migration/data
    validate-on-migrate: true
    schemas:
      - helmcm
    default-schema: helmcm
server:
  port: 8081